filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
    paths: {  }
tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit
        config_path: null
        only_changesets: false
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'
before_commands: {  }
after_commands: {  }
artifacts: {  }