filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
        - 'tests/*'
    paths: {  }
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit
        config_path: null
        only_changesets: false
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
    php_mess_detector: true
    php_code_sniffer: true
changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'
before_commands: {  }
after_commands: {  }
artifacts: {  }