filter:
    excluded_paths:
        - 'vendor/*'
    paths: {  }
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_code_coverage:
        test_command: phpunit -c tests/
    external_code_coverage: true
    php_mess_detector: true
    php_cpd:
        command:              ~
        excluded_dirs:        []
        min_lines:            5
        min_tokens:           70
        enabled:              false
        filter:
            paths:                []
            excluded_paths:       []
    php_pdepend: true
after_commands: {  }
artifacts: {  }